volumes:
  pg_data:
  static:
  media:


services:
  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kozlovl/foodgram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media

  frontend:
    env_file: .env
    image: kozlovl/foodgram_frontend
    command: sh -c "cp -r /app/build/. /static/"
    volumes:
      - static:/frontend_static
  gateway:
    image: kozlovl/foodgram_gateway
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/media
