# Generated by Django 4.2.21 on 2025-05-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_favorite_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_user_shoppingcart_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_user_and_subscribed_user',
        ),
    ]
