# Generated by Django 4.2.21 on 2025-05-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_name_alter_recipe_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users/images/', verbose_name='Аватар'),
        ),
    ]
